apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260519-004617-2c0cxhvlfjku-service
spec:
  selector:
    app: enterprise-system-20260519-004617-2c0cxhvlfjku
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
